global using System;
global using System.Text;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Swashbuckle.AspNetCore.Annotations;
global using System.Linq;
global using System.Text.Json.Serialization;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Identity;
global using CropDeal.AppDB;
global using CropDeal.Interface;
global using CropDeal.Models;
global using CropDeal.Repository;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using System.Security.Claims;
global using System.IdentityModel.Tokens.Jwt;
global using CropDeal.DTO;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Cryptography;
global using Razorpay.Api;
global using CropDeal.Controllers;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using ClosedXML.Excel;
// global using CropDeal.AppDB.Seed;
// global using Swashbuckle.AspNetCore.Annotations;

global using QuestPDF.Fluent;
global using QuestPDF.Infrastructure;
global using QuestPDF.Helpers;
global using QuestPDF.Drawing;
global using CropDeal.Models;
global using System.Net;
global using System.Net.Mail;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using System.Text.Json;
global using CropDeal.Middlewares;
// global using SelectPdf;
// global using Newtonsoft.Json;