namespace CropDeal.Controllers;

[Authorize(Roles = "Admin")]
[ApiController]
[Route("api/[controller]")]
public class ReportController : ControllerBase
{
    private readonly IReportRepository _reportRepo;
    private readonly CropDealDBContext _context;

    public ReportController(IReportRepository reportRepo, CropDealDBContext context)
    {
        _reportRepo = reportRepo;
        _context = context;
    }

    [HttpPost("Admin/GenerateReport/{dealerId}")]
    public async Task<IActionResult> GenerateReport(Guid dealerId, [FromBody] string filter = null)
    {
        var adminIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
        if (adminIdClaim == null)
        {
            return Unauthorized("Admin ID not found.");
        }
        var adminId = Guid.Parse(adminIdClaim.Value);
        var report = await _reportRepo.GenerateDealerReportAsync(adminId, dealerId);
        return Ok(report);
    }

    [HttpGet("Admin/GetAllReports")]
    public async Task<IActionResult> GetAll()
    {
        var reports = await _reportRepo.GetAllAsync();
        if (reports != null)
        {
            return Ok(reports);
        }
        return BadRequest();
    }

    [HttpGet("Admin/GetReportById/{id}")]
    public async Task<IActionResult> GetById(Guid id)
    {
        var report = await _reportRepo.GetByIdAsync(id);
        if (report == null)
        {
            return NotFound();
        }
        return Ok(report);
    }

    // [HttpPost]
    // public async Task<IActionResult> Add([FromBody] Report report)
    // {
    //     var result = await _reportRepo.AddAsync(report);
    //     return Ok(result);
    // }

    // [HttpPut("{id}")]
    // public async Task<IActionResult> Update(Guid id, [FromBody] Report report)
    // {
    //     var result = await _reportRepo.UpdateAsync(id, report);
    //     return result == null ? NotFound() : Ok(result);
    // }

    // [HttpDelete("{id}")]
    // public async Task<IActionResult> Delete(Guid id)
    // {
    //     var deleted = await _reportRepo.DeleteAsync(id);
    //     return deleted ? NoContent() : NotFound();
    // }

    [HttpGet("export/{reportId}")]
    public async Task<IActionResult> ExportReportToExcel(Guid reportId)
    {
        var report = await _context.Reports.FindAsync(reportId);

        if (report == null)
        {
            return NotFound("Report not found");
        }

        using var workbook = new XLWorkbook();
        var worksheet = workbook.Worksheets.Add("Dealer Report");

        // Write report title and metadata
        worksheet.Cell("A1").Value = "Report Title:";
        worksheet.Cell("B1").Value = report.Title;

        worksheet.Cell("A2").Value = "Generated By:";
        worksheet.Cell("B2").Value = report.GeneratedBy.ToString();

        worksheet.Cell("A3").Value = "Generated For:";
        worksheet.Cell("B3").Value = report.GeneratedFor.ToString();

        worksheet.Cell("A4").Value = "Created At:";
        worksheet.Cell("B4").Value = report.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss");

        

        // Leave one row gap before table
        int tableStartRow = 6;

        // Table headers
        worksheet.Cell(tableStartRow, 1).Value = "Dealer Name";
        worksheet.Cell(tableStartRow, 2).Value = "Crop Name";
        worksheet.Cell(tableStartRow, 3).Value = "Quantity";
        worksheet.Cell(tableStartRow, 4).Value = "Price";
        worksheet.Cell(tableStartRow, 5).Value = "Date";
        worksheet.Cell(tableStartRow, 6).Value = "Status";

        var contentLines = report.Content.Split(Environment.NewLine);
        int row = tableStartRow + 1;

        foreach (var line in contentLines)
        {
            var values = line.Split(',');

            for (int i = 0; i < values.Length; i++)
            {
                // Extract value after colon
                var parts = values[i].Split(':');
                var value = parts.Length > 1 ? parts[1].Trim() : values[i].Trim();
                worksheet.Cell(row, i + 1).Value = value;
            }

            row++;
        }

        // Optional formatting
        worksheet.Columns().AdjustToContents();

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        stream.Seek(0, SeekOrigin.Begin);

        return File(stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            "Dealer_Report.xlsx");
    }


}
